#import './account.gql'
# 进入用户中心需要初始化的数据
query initUserCenter($type: Int) {
  # 用户信息
  ...userInfoQuery
  # 订单状态
  orderQuery {
    getOrderStatus (type: $type) {
      code
      name
    }
  }
  # 快递公司列表
  logisticsCompanyQuery {
    logisticsCompanyList {
      id
      name
    }
  }
}